services:
    marttiphpbb.calendarmono:
        class: marttiphpbb\calendarmono\repository\events
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarinput.tag_listener:
        class: marttiphpbb\calendarinput\event\tag_listener
        tags:
            - { name: event.listener }
