services:
    marttiphpbb.calendarmono:
        class: marttiphpbb\calendarmono\repository\events
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'
